package masterdev.br.com.zup.model;

public enum CardNameEnum {
    ANTIVIRUS("ANTIVIRUS"),CHANGEEXPERIENCEPOWER("CHANGE EXPERIENCE POWER"),COFFEEBREAK("COFFEE BREAK"),
    COFFEE("COFFEE"),DEBUG("DEBUG"),STACKOVERFLOW("STACK OVERFLOW"),STACKTRACE("STACKTRACE"),FRAMEWORK("FRAMEWORK"),
    TECHLEADPOWER("TECH LEAD POWER"),TEST("TEST"),
    GOLPENAOCONSIGO("GOLPE NÃO CONSIGO"),CODIGOMALESCRITO("CODIGO MAL ESCRITO"),PERDEUADAILY("PERDEU A DAILY"),
    ENDPOINTBATENDOERRADO("ENDPOINTBATENDOERRADO"),PERDENDOCONTATO("PERDENDO CONTATO"),
    MAADMDETEMPO("MÁ ADMINISTRAÇÃO DE TEMPO"),GIT("GIT"),PANDEMIA("PAMDEMIA"),SEMTESTE("SEM TESTE");
    private String name;

    CardNameEnum(String name) {
        this.name = name;
    }
}
